language: csharp

os:
 - linux
 - osx

mono: none
dotnet: 1.0.4
dist: trusty

before_install:
  - cd neo.UnitTests
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ulimit -n 2048; rvm install 2.3.5; rvm use 2.3.5; fi

script:
 - dotnet restore
 - dotnet test
